# Production context: All deploys from the main
# repository branch will inherit these settings.
[context.production]
  command = "make production"
  [context.production.environment]
    REACT_APP_WEATHER_API_KEY = "8ddec521d125e33190069c4c5e381104"